


-- create one table of the mean and standard deviation of the sentiment scores for each table 

SELECT 'FED_BEIGEBOOK' AS TABLE_NAME, AVG(sentiment) AS MEAN, STDDEV(sentiment) AS STDDEV
FROM FED_BEIGEBOOK
UNION
SELECT 'FED_SPEECHES' AS TABLE_NAME, AVG(sentiment) AS MEAN, STDDEV(sentiment) AS STDDEV
FROM FED_SPEECHES
UNION
SELECT 'FED_MINUTES' AS TABLE_NAME, AVG(sentiment) AS MEAN, STDDEV(sentiment) AS STDDEV
FROM FED_MINUTES
UNION
SELECT 'ECB_SPEECHES' AS TABLE_NAME, AVG(sentiment) AS MEAN, STDDEV(sentiment) AS STDDEV
FROM ECB_SPEECHES
UNION
SELECT 'ECB_MONETARY_POLICY_DECISIONS' AS TABLE_NAME, AVG(sentiment) AS MEAN, STDDEV(sentiment) AS STDDEV
FROM ECB_MONETARY_POLICY_DECISIONS
UNION
SELECT 'ECB_ECONOMIC_BULLETIN' AS TABLE_NAME, AVG(sentiment) AS MEAN, STDDEV(sentiment) AS STDDEV
FROM ECB_ECONOMIC_BULLETIN
ORDER BY TABLE_NAME ASC;

